name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: SurgeX_DB
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: --health-cmd "mysqladmin ping -hlocalhost --silent" --health-interval 10s --health-timeout 30s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Wait for MySQL to be ready
      run: |
        echo "Waiting for MySQL to be ready..."
        for i in {1..60}; do
          if mysqladmin ping -hlocalhost -uroot -proot --silent; then
            echo "MySQL is ready."
            break
          else
            echo "MySQL not ready yet. Waiting..."
            sleep 10
          fi
        done

    - name: Set up MySQL
      run: |
        mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS SurgeX_DB;
                                USE SurgeX_DB;
                                CREATE TABLE IF NOT EXISTS user (
                                  username CHAR(50) NULL,
                                  passwd CHAR(50) NULL
                                ) ENGINE=InnoDB;'

    - name: Build project
      run: ./build.sh
